### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by shravan2x** [bchavez/Coinbase#25]
Are there any plans for this library to support .NET Core?

**Comment by bchavez** [comment]
Hello @shravan2x ,

There are no plans as of yet. However, I would accept a PR that would bring it in line with .NET Standard 1.3 or 2.0. Standard 2.0 would likely have the least friction in migrating forward.

IIRC, in order to make it fully compliant with .NET Core, the `RestSharp` dependency would need to be removed and replaced with something more modern like `Flurl`.

If you're up to the task, let me know.

Thanks,
Brian

:crown: :gem: ***["I know everything that shine ain't always gold..."](https://www.youtube.com/watch?v=7xzU9Qqdqww)***

**Comment by shravan2x** [comment]
I don't have very much time to spare right now, but if there's no plan to do it and no alternative library that has it, I'll give it a shot.

**Comment by Serjster** [comment]
I have an ASP.NET Core version that I created: https://github.com/SaganMarketing/CoinbaseNetCore/

**Comment by bchavez** [comment]
**.NET Core** (based on **.NET Standard 2.0**) support is now in **Coinbase** `v3.0.1`.

https://www.nuget.org/packages/Coinbase/3.0.1

Thanks,
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***
