### ISSUE TITLE
 Create New Address

### ISSUE THREAD

**Issue by nvkhanh0412** [bchavez/Coinbase#28]
i using code : api.SendRequest("wallet/MyWalletID/addresses", Method.POST);
but it return Address existing, this is not new address.
please help me.

**Comment by bchavez** [comment]
Hello @nvkhanh0412,

Try sending an empty `{}` content body, or `{"name": "My New Address Label"}` in the `POST` body.

Other than that, I'm not sure I can help you because it looks like what your doing should work: https://developers.coinbase.com/api/v2#create-address

If all else fails, you'll want to get in contact with Coinbase's technical support api@coinbase.com. Feel free to re-open the issue if you find something wrong with the source code in this repository.

Thanks,
Brian

:fallen_leaf: :leaves: **[Distance - Falling (ft Alys Be)](https://www.youtube.com/watch?v=WIfwIv4wNCE)***

**Comment by nvkhanh0412** [comment]
Thank's for support. But it don't use.
