### ISSUE TITLE
GetNextPageAsync on ICoinbaseClient

### ISSUE THREAD

**Issue by Mabiro** [bchavez/Coinbase#71]
Hi, I have just started using this library and I was wondering if there was any plan to include methods like GetNextPageAsync on the ICoinbaseClient interface?

GetNextPageAsync is quite useful, but it's not something that can be used when injecting a ICoinbaseClient  instead of CoinbaseClient.

Thank you for this, it's been really nice to use so far!

**Comment by bchavez** [comment]
Hi @Mabiro ,

Thank you for raising the issue. I don't have any plans to support `.GetNextPageAsync`. I think supporting such a feature would probably require managing some state inside `ICoinbaseClient` per request.  Or possibly building infrastructure around the response object/request API to re-hydrate page state values to retrieve the next page for a given request.

If you have any sample code about how you envision this would work, feel free to continue the discussion. I'm always open to new ideas or methods that can enhance usability. However, I do have to balance maintainability as well - which turns out to be my primary concern maintaining these Coinbase APIs.

Thanks,
Brian
