### ISSUE TITLE
Transaction Transfer returning empty

### ISSUE THREAD

**Issue by khinklenj** [bchavez/Coinbase#79]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            | latest        |
| .NET Core?                   |                 |
| .NET Full Framework?   |                 |
| Windows OS?              | 10                  |
| Linux OS?                    |                  |
| Visual Studio?              |  2019                |

### What is the expected behavior?
Return Transfer data
### What is the actual behavior?
Returned null
### How do you reproduce the issue?
Tried to do a transfer
### Do you have a unit test that can demonstrate the bug?
Yes
### Can you identify the location in the source code where the problem exists?
No
![Transfer Error](https://user-images.githubusercontent.com/6447184/110660649-c331e480-8191-11eb-8106-1c1d5368732a.png)

**Comment by bchavez** [comment]
Hi @khinklenj,

You'll have to provide HTTP diagnostics of what is going on over the wire.

There could be an issue with the response object (as a JSON string) that isn't getting serialized in the correct way leading to an empty or null `.Data` field.

Coinbase is known for changing JSON contract types out of the blue without telling anyone. You'll have to debug this further with Fiddler. Check the wiki page here: https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler

Once you have Fiddler debugging proxy working; inspect the RAW JSON and see if that matches up with what we expect in the Coinbase library. If something doesn't match up; you have two options:
1) provide all diagnostics and screenshots about what you think the problem is, and I can try to fix it in a few weeks
2) Make a PR: make the code fix, verify it works on your computer, write a unit test following similar conventions and coding style that are in this project. Once you have a PR up for review, I will review, test, and merge and make a new release.

Thanks,
Brian
